-- Phase 12 (AI enrichment escalation tier): a short human-readable preview
-- of each file, generated by the LLM classifier when it runs. Stored
-- directly on `files` (rather than only inside
-- classification_results.raw_output) so list views like the Files page can
-- show a one-line description without joining/parsing JSON per row.
--
-- Nothing here is required -- the rule-based classifier (Phase 5) keeps
-- working exactly as before when these columns are null, i.e. when AI
-- classification is disabled or hasn't run yet for a given file.

ALTER TABLE files
  ADD COLUMN IF NOT EXISTS ai_short_title   TEXT,
  ADD COLUMN IF NOT EXISTS ai_summary       TEXT,
  ADD COLUMN IF NOT EXISTS ai_entities      JSONB,
  ADD COLUMN IF NOT EXISTS ai_classified_at TIMESTAMPTZ;

COMMENT ON COLUMN files.ai_short_title IS
  'LLM-generated specific title, e.g. "Q3 2024 Vendor Invoice - Acme Corp" -- distinct from the taxonomy-bucket canonical name in namingService.';
COMMENT ON COLUMN files.ai_summary IS
  'One or two sentence LLM-generated plain-English description of the document, for list-view scanning without opening the file.';
COMMENT ON COLUMN files.ai_entities IS
  'Structured extraction from the LLM pass: { party, date_or_period, identifier }. Used by namingService to build more specific canonical names than subject/type alone.';
